### ISSUE TITLE
[PE-D][Tester A] Ambiguous writing & grammar in Person card

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W13-2/tp#116]
Not very clear on why First is capitalised, maybe to make it clearer could capitalise both First & Bracket so it seems part of a more official group?

Also not very clear also on what the First bracket means also, what does the First bracket signify? Could not find quick information by searching the term in the User Guide so maybe a clearer explanation is needed on this part

![Screenshot 2022-10-28 at 4.15.05 PM.png](https://raw.githubusercontent.com/Jnwkm/ped/main/files/233f3d03-52a7-457f-89de-bf20b7e2b36a.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Jnwkm/ped#1

**Comment by loyhongshenggg** [comment]
Describe and explain in UG - first/second/third bracket
