### ISSUE TITLE
[PE-D][Tester D] Hard to read command summary

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W13-2/tp#136]
![image.png](https://raw.githubusercontent.com/Guanzhou03/ped/main/files/78106657-0be9-44b7-9263-5860fe696442.png)

Perhaps the command summary's readability can be improved (into a table form maybe)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Guanzhou03/ped#6

**Comment by loyhongshenggg** [comment]
resolved
