### ISSUE TITLE
[PE-D][Tester C] Version history not updated

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W13-2/tp#144]
![Screenshot 2022-10-28 at 4.49.18 PM.png](https://raw.githubusercontent.com/chantellyu/ped/main/files/87a69a32-4d42-4348-8df8-74f140166fca.png)

The version history is still 0.2 and remains not updated to the current version. This does not match the release file.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: chantellyu/ped#7

**Comment by marcusczh** [comment]
Resolved
