### ISSUE TITLE
[PE-D][Tester C] No way to view exact income of client

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W13-2/tp#145]
![Screenshot 2022-10-28 at 4.51.29 PM.png](https://raw.githubusercontent.com/chantellyu/ped/main/files/f1599322-684a-4c7a-ab07-f9a8eeee1e99.png)

There is no way to access the exact income of the client which could be important to see as even within income brackets there is variation.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: chantellyu/ped#8

**Comment by cowlinn** [comment]
Need discuss this!

**Comment by loyhongshenggg** [comment]
Hmm interesting, I wonder if we're able to implement this in v1.4

**Comment by loyhongshenggg** [comment]
Explain brackets in UG
