### ISSUE TITLE
[PE-D][Tester C] Message shown missing spacing

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W13-2/tp#161]
![Screenshot 2022-10-28 at 5.22.54 PM.png](https://raw.githubusercontent.com/chantellyu/ped/main/files/af9f982e-b7e8-47c1-b5d0-38b4c8477986.png)

Lacking proper spacing in client field.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: chantellyu/ped#13

**Comment by loyhongshenggg** [comment]
![image](https://user-images.githubusercontent.com/97422591/198883056-78289f18-62ba-4099-ad75-d7f82ac160b7.png)

Change UG screenshot
